### ISSUE TITLE
Should some RiaAverageCarPrice int parameters be boolean?

### ISSUE THREAD

**Issue by serebrov** [al-serebrov/python-auto-ria#3]
There are some parameters, that look like they are boolean (True / False):

``` 
myCarAveragePrice = RiaAverageCarPrice(
    ....   
    custom=0,
    damage=0,
    under_credit=0,
    confiscated=0,
    on_repair_parts=0
)
```

These look like boolean parameters, but they are handled as integers.
Can they be something different than 0 or 1?
If not - they should be `bool` and not `int`.

**Comment by al-serebrov** [comment]
Agree.
They're now implemented as stated in auto.ria API description, where they're `int`.

**Comment by al-serebrov** [comment]
Changes made and merged to master
